# Generated by Django 4.1.5 on 2023-01-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_booked_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='history',
            field=models.TextField(blank=True, verbose_name='История клиента'),
        ),
    ]
