# Generated by Django 4.1.5 on 2023-01-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_booked_client_alter_booked_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='datetime',
            new_name='datetime_booked',
        ),
    ]
