# Generated by Django 4.1.5 on 2023-01-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_datetime_booked_datetime_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='datetime_booked',
            new_name='datetime',
        ),
    ]
