# Generated by Django 4.1.5 on 2023-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_datetime_booked_booked_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(max_length=13, verbose_name='Телефон'),
        ),
    ]
