# Generated by Django 4.1.5 on 2023-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='datetime',
            field=models.DateTimeField(unique=True, verbose_name='Дата бронирования'),
        ),
    ]
